# site settings
title: KoriKosmos
subtitle: aka that one guy that really loves vtubers
email: kori@korikosmos.moe
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://korikosmos.moe" # the base hostname & protocol for your site
author: KoriKosmos (Maan Meher)
street_address: 111 Bond Street
city: Egham
state: N/A
zip_code: TW20 0PU
country: United Kingdom
phone: +447484345619

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/KoriKosmos
# GitLab:
# Google-Plus:
  Instagram: https://www.instagram.com/KoriKosmos/
  LinkedIn: https://www.linkedin.com/in/maan-meher-449094a0/
  Twitter: https://twitter.com/KoriKosmos
# Facebook:
# Slack:
  Discord: http://discord.com/users/293023468432130059

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
