name: Update Tracks

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  push:
    branches:
      - redesign

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Fetch latest tracks
        run: node fetch-tracks.mjs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Update latest tracks' || echo "No changes to commit"
          git push origin redesign
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
